name: Update Stats Cards
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # 1. Generate the Main Stats Card (Private + Org)
      - name: Generate General Stats
        uses: stats-organization/github-readme-stats-action@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          card: stats
          path: profile/stats.svg
          options: "username=brittleru&theme=react&include_all_commits=true&count_private=true&hide_border=true&custom_title=GitHub%20Activity&show_icons=true"

      # 2. Generate the Top Languages Card
      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v1
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          card: top-langs
          path: profile/top-langs.svg
          options: "username=brittleru&theme=react&layout=compact&hide_border=true&langs_count=10&size_weight=0.6&count_weight=0.4"

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push